name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Start 🔧
        run: npm start

      # - name: Lint 🧐
      #   run: npm run lint
        
      # - name: Error
      #   run: echo "error!"; exit 1

      - name: Build 🏗️
        run: npm build

      # - name: Test 🚨
      #   run: npm test
